project_id = "ohiudeaxangdgpqpyoqx"

[functions.send-push]
verify_jwt = false

[functions.schedule-motivation]
verify_jwt = false

[functions.gemini-analyze]
verify_jwt = true

[functions.mcq-generate]
verify_jwt = true

[functions.mcq-embed]
verify_jwt = true
